### ISSUE TITLE
Usecase for getAll()

### ISSUE THREAD

**Issue by Saketme** [f2prateek/rx-preferences#111]
Hey folks, does rx-preferences intentionally not include a way to observe all items? If not, I'd like to contribute by sending a PR.

**Comment by JakeWharton** [comment]
With what type would you do this? And what's the use case?

**Comment by Saketme** [comment]
My use case was to observe all changes and get a stream of `Map<String, ?>`. Although doing it manually requires only 5-6 lines of code, I was hoping to keep things consistent and do it through rx-preferences.

**Comment by JakeWharton** [comment]
Wouldn't it be Pair<String, ?> since the listener only delivers changes one
at a time regardless if you update 1 or 100 in a single edit.

**Comment by Saketme** [comment]
Sure, `Pair<String, ?>` if you want to receive the changes individually, but the callback from shared preference's listener can also be mapped to a map of all items present in the file.

**Comment by JakeWharton** [comment]
You want the entire listing? I'm not sure we should encourage that... The
simple version of that is going to create a lot of a GC garbage creating
the map each time. A correctly implemented version requires either a
persistent data structure so that when a single entry changes we don't
create an entire new map, or it requires a custom Map subtype which is a
facade over the backing SharedPreferences object to try and do as much
lazily as possible.

**Comment by Saketme** [comment]
Apologies for replying late. Allocating a map on every change does sound very expensive. I just realized that `SharedPreferences` does not create an immutable copy of its map to avoid this problem.

A persistent data structure or a custom Map subtype sounds more effort than simply bypassing rx-preferences and implementing a change listener manually. 

I'll close this issue, thanks for replying!
