### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by justintuchek** [f2prateek/rx-preferences#126]
Hey 👋 any rough estimate on when Android X support would be available?

Checked it out in [master](https://github.com/f2prateek/rx-preferences/commit/e338b4e6cee9c0c7b850be86ab41ed7b39a3637e) but hasn't yet been deployed. Anything I can do to help?

**Comment by f2prateek** [comment]
Can you try the snapshot builds and report if everything looks ok? (instructions would be similar to https://github.com/segmentio/analytics-java#snapshots)

**Comment by justintuchek** [comment]
Sure - I can do that 👍 

Would there be any testing contributions that you would find helpful for verification of future releases? Maybe something in Espresso? _(realizing that blows up the simplicity of the current testing pipeline and Travis)_

**Comment by f2prateek** [comment]
I feel reasonably confident about the unit tests in place. I'm not sure how much value espresso/UI tests would add to this library, but would be open to it if there's a strong reason.

Asking for manual verification in this case mostly as a sanity check, because [this change in particular](https://github.com/f2prateek/rx-preferences/pull/124) changed a lot of the tooling that could cause issues depending on the build environment of your app.

**Comment by technoir42** [comment]
@f2prateek no issues with 2.0.1-beta1, although it would be great to finally see a stable release with AndroidX.

**Comment by f2prateek** [comment]
Thanks for the reminder - just cut release 2.0.1 promoting the changes from the beta to stable.
