### ISSUE TITLE
Make Preference into an interface

### ISSUE THREAD

**Issue by dalewking** [f2prateek/rx-preferences#32]
Preference itself is a final class that can only be created through static methods in another class. You have created a unit test nightmare. You should change Preference into an interface and extract the implementation to another class. When using dependency injection the classes needing access to the Preference would inject the interface instead of a concrete class. That makes creating mock preferences for unit testing a breeze.

Without this, unit testing of classes that depend on a preference is much more difficult. It would require mocking SharedPreferences but having to capture the listener that is registered internally for preference changes.

**Comment by JakeWharton** [comment]
I'm having deja vu! Let me go copy/paste my other responses.

**Comment by NateWickstrom** [comment]
Looks like this issue is not a priority, but i'd also appreciate the extra layer of abstraction.  Among other things, dependency inversion would make testing much easier.  Perhaps it's something you can add with RxJava 2..

**Comment by f2prateek** [comment]
See https://github.com/f2prateek/rx-preferences/blob/2.x/rx-preferences/src/main/java/com/f2prateek/rx/preferences2/Preference.java

**Comment by dalewking** [comment]
Thank you for getting around to doing this. I would still like to see a ReadOnlyPreference super interface for Preference that declares all the methods except for set, delete, and asConsumer to be able to inject a read only version of the preference to limit who has the ability to modify the preference as I suggested in #31

**Comment by f2prateek** [comment]
I do see how it could be useful in the cases you're describing - I just don't think it's general enough to incur the overhead in the core library. So I don't think a read only interface is the responsibility of this library. That should live in your application. And you can just as easily observe to `Observable<Foo>` instead of dealing with a Preference object.

**Comment by dalewking** [comment]
That is assuming that the only way anyone would use the preference in a read only scenario is as an observable, but in some cases you want to use the get method and you don't have any interface that exposes the get method without also exposing the set method.

I am not sure how adding another level of interface is any significant "overhead in the core library". Anyone that wants a read only access to the preference it would result in a large overhead in their software. I speak from experience with 1.x version of this library since I already have a wrapper class that I use to  wrap every instance an RX preference in order to have the proper interfaces.

**Comment by f2prateek** [comment]
The overhead is just my mental overhead. Instead of a single preference type there's now a Readable and a Writeable preference type and users have to understand the difference. And what if a consumer wants to just be abel to edit a preference, but not delete it. Should there now be 3 types — WriteablePref, EditablePref and DeleteablePref?

The library should give you the tools to make preferences reactive. I think anything on top of that is your responsibility.

**Comment by dalewking** [comment]
There is still only a single preference Preference, it just has a super interface that has a subset of the API. The problem with saying it is my responsibility is that I cannot insert a super interface. The only way I could expose a read only interface for preferences is to create my own interface and then write a wrapper that wraps your preference and delegates to it.

**Comment by f2prateek** [comment]
Defining an interface for every method is not a reasonable solution for this (or any) library.

Building your own interfaces by composing this library with your desired behavior is the right solution. Implementating this is very much your responsibility, just as you would have had to do if you were using SharedPreferences natively since there is no ReadableSharedPreferences/WriteableSharedPrefrences type.

**Comment by f2prateek** [comment]
`Preference` is an interface in `2.0.0-RC1`.
