### ISSUE TITLE
Make an emmit for any setting

### ISSUE THREAD

**Issue by m4xp1** [f2prateek/rx-preferences#93]
Why do I only see changes in the value? Is it possible to make an emmit for any setting? Example:

```
Preference<Boolean> preference = preferences.getBoolean(KEY_FOO, true);
preference.set(true);
preference.set(true);
preference.set(true);
```

Emmit only onse (( It would be more convenient every time! Thanks!

```
  /**
   * Observe changes to this preference. The current value or {@link #defaultValue()} will be
   * emitted on first subscribe.
   */
  @CheckResult @NonNull Observable<T> asObservable();
```

**Comment by NightlyNexus** [comment]
Can you make a failing test case?
That sounds like a bug because that's not the behavior of [OnSharedPreferenceChangeListener](https://developer.android.com/reference/android/content/SharedPreferences.OnSharedPreferenceChangeListener.html#onSharedPreferenceChanged(android.content.SharedPreferences,%20java.lang.String)) registerOnSharedPreferenceChangeListener).

**Comment by m4xp1** [comment]
I checked the behavior "OnSharedPreferenceChangeListener" it does not call "onSharedPreferenceChanged" if the same value is set. I close the task.
